//! Wavefront OBJ loading into the engine's [`Scene`]/[`Mesh`] types.
//!
//! [`load_obj`] parses an `.obj` file with [`tobj`], triangulating polygonal faces, grouping the
//! file's objects/groups into separate [`Mesh`]es, and generating flat face normals when the file
//! provides none (so shading works). The loader is pure geometry: it knows nothing about
//! rendering, the terminal, or materials — MTL/textures are intentionally out of scope.
//!
//! Malformed or missing files yield an [`Err`] built from the crate [`Error`]; the loader never
//! panics on input-derived data.
//!
//! # Example
//!
//! ```no_run
//! use rgfx_3d::load_obj;
//!
//! let scene = load_obj("model.obj")?;
//! println!("{} meshes, {} triangles", scene.meshes.len(), scene.triangle_count());
//! # Ok::<(), rgfx_core::Error>(())
//! ```

use std::fmt;
use std::path::Path;

use glam::Vec3;
use rgfx_core::{BoundingBox, BoundingSphere, Error, Mesh, Result, Scene, Vertex};

/// Loads a Wavefront OBJ file into a [`Scene`].
///
/// Each object/group in the file becomes one [`Mesh`]; polygonal faces are triangulated. When a
/// mesh lacks normals, per-vertex normals are generated by accumulating adjacent face normals so
/// the renderer can shade it. Vertex positions are taken directly from the file (no transform is
/// applied). The returned scene's [`name`](Scene::name) is the file stem.
///
/// # Errors
///
/// Returns [`Error::Decode`] if the file is missing, cannot be read, or is malformed — the
/// underlying [`tobj::LoadError`] message is preserved.
pub fn load_obj(path: impl AsRef<Path>) -> Result<Scene> {
    let path = path.as_ref();
    let options = tobj::LoadOptions {
        single_index: true,
        triangulate: true,
        ignore_points: true,
        ignore_lines: true,
    };

    let (models, _materials) =
        tobj::load_obj(path, &options).map_err(|e| Error::Decode(format!("obj: {e}")))?;

    let mut meshes = Vec::with_capacity(models.len());
    for model in models {
        meshes.push(convert_mesh(&model.mesh)?);
    }

    let name = path
        .file_stem()
        .map(|s| s.to_string_lossy().into_owned())
        .unwrap_or_default();

    Ok(Scene::new(name, meshes))
}

/// Converts a single `tobj` mesh into an engine [`Mesh`], generating normals when absent.
fn convert_mesh(mesh: &tobj::Mesh) -> Result<Mesh> {
    if mesh.positions.len() % 3 != 0 {
        return Err(Error::Geometry(
            "obj: position buffer length is not a multiple of 3".into(),
        ));
    }
    if mesh.indices.len() % 3 != 0 {
        return Err(Error::Geometry(
            "obj: index buffer length is not a multiple of 3 after triangulation".into(),
        ));
    }

    let vertex_count = mesh.positions.len() / 3;
    // With `single_index`, normals (when present) are reindexed to align with positions.
    let has_normals = mesh.normals.len() == mesh.positions.len();

    let mut vertices = Vec::with_capacity(vertex_count);
    for i in 0..vertex_count {
        let position = Vec3::new(
            mesh.positions[i * 3],
            mesh.positions[i * 3 + 1],
            mesh.positions[i * 3 + 2],
        );
        let normal = if has_normals {
            Vec3::new(
                mesh.normals[i * 3],
                mesh.normals[i * 3 + 1],
                mesh.normals[i * 3 + 2],
            )
        } else {
            Vec3::ZERO
        };
        vertices.push(Vertex::new(position, normal));
    }

    // Validate indices before we trust them for normal generation.
    for &idx in &mesh.indices {
        if idx as usize >= vertex_count {
            return Err(Error::Geometry(format!(
                "obj: vertex index {idx} out of range (have {vertex_count} vertices)"
            )));
        }
    }

    let indices = mesh.indices.clone();
    if !has_normals {
        generate_normals(&mut vertices, &indices);
    }

    Ok(Mesh::new(vertices, indices))
}

/// Generates per-vertex normals from triangle faces, in place.
///
/// Each triangle contributes its (area-weighted) geometric normal to its three vertices; the
/// accumulated normals are then normalized. Degenerate triangles contribute nothing, and vertices
/// touched by no valid face keep a zero normal rather than producing `NaN`.
fn generate_normals(vertices: &mut [Vertex], indices: &[u32]) {
    for v in vertices.iter_mut() {
        v.normal = Vec3::ZERO;
    }

    for tri in indices.chunks_exact(3) {
        let (i0, i1, i2) = (tri[0] as usize, tri[1] as usize, tri[2] as usize);
        let p0 = vertices[i0].position;
        let p1 = vertices[i1].position;
        let p2 = vertices[i2].position;
        // Length encodes twice the triangle area, so larger faces weigh more.
        let face = (p1 - p0).cross(p2 - p0);
        vertices[i0].normal += face;
        vertices[i1].normal += face;
        vertices[i2].normal += face;
    }

    for v in vertices.iter_mut() {
        v.normal = v.normal.normalize_or_zero();
    }
}

/// Summary statistics for a loaded [`Scene`], for the future `info` command.
///
/// Bounds are `None` for an empty scene (no vertices).
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct ObjStats {
    /// Number of meshes (OBJ objects/groups) in the scene.
    pub meshes: usize,
    /// Total vertex count across all meshes.
    pub vertices: usize,
    /// Total triangle count across all meshes.
    pub triangles: usize,
    /// The axis-aligned bounding box enclosing every mesh.
    pub bounds: Option<BoundingBox>,
    /// The bounding sphere used for auto-framing the camera.
    pub bounding_sphere: Option<BoundingSphere>,
}

impl ObjStats {
    /// Computes stats (counts and bounds) for a scene.
    pub fn from_scene(scene: &Scene) -> Self {
        let bounds = scene.bounding_box();
        Self {
            meshes: scene.meshes.len(),
            vertices: scene.vertex_count(),
            triangles: scene.triangle_count(),
            bounds,
            bounding_sphere: bounds.map(|b| b.bounding_sphere()),
        }
    }
}

impl fmt::Display for ObjStats {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "{} mesh(es), {} vertices, {} triangles",
            self.meshes, self.vertices, self.triangles
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    /// A unit cube centered at the origin, 8 shared corner vertices, no normals, quad faces.
    const CUBE_OBJ: &str = "\
o cube
v -1 -1 -1
v  1 -1 -1
v  1  1 -1
v -1  1 -1
v -1 -1  1
v  1 -1  1
v  1  1  1
v -1  1  1
f 1 2 3 4
f 5 8 7 6
f 1 5 6 2
f 2 6 7 3
f 3 7 8 4
f 4 8 5 1
";

    /// Writes `contents` to a uniquely named temp file and returns its path.
    fn temp_obj(contents: &str, tag: &str) -> std::path::PathBuf {
        let mut path = std::env::temp_dir();
        let unique = format!(
            "rgfx-obj-{}-{}-{:?}.obj",
            std::process::id(),
            tag,
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        );
        path.push(unique);
        let mut file = std::fs::File::create(&path).unwrap();
        file.write_all(contents.as_bytes()).unwrap();
        path
    }

    #[test]
    fn loads_cube_fixture_with_expected_counts_and_bounds() {
        let scene = load_obj("tests/assets/cube.obj").expect("cube.obj should load");

        assert_eq!(scene.meshes.len(), 1, "single object -> single mesh");
        assert_eq!(scene.vertex_count(), 8, "8 shared corners");
        // 6 quad faces triangulated -> 12 triangles.
        assert_eq!(scene.triangle_count(), 12);

        let bb = scene.bounding_box().expect("non-empty scene has bounds");
        assert_eq!(bb.min, Vec3::splat(-1.0));
        assert_eq!(bb.max, Vec3::splat(1.0));

        let stats = ObjStats::from_scene(&scene);
        assert_eq!(stats.meshes, 1);
        assert_eq!(stats.vertices, 8);
        assert_eq!(stats.triangles, 12);
        let sphere = stats.bounding_sphere.expect("has sphere");
        assert!((sphere.radius - 3.0_f32.sqrt()).abs() < 1e-5);
        assert!(stats.to_string().contains("12 triangles"));
    }

    #[test]
    fn generates_unit_normals_when_absent() {
        let path = temp_obj(CUBE_OBJ, "normals");
        let scene = load_obj(&path).expect("embedded cube should load");
        std::fs::remove_file(&path).ok();

        let mesh = &scene.meshes[0];
        assert!(!mesh.vertices.is_empty());
        for v in &mesh.vertices {
            assert_ne!(v.normal, Vec3::ZERO, "normal must be generated");
            assert!(
                (v.normal.length() - 1.0).abs() < 1e-4,
                "generated normal must be unit length, got {}",
                v.normal.length()
            );
        }
    }

    #[test]
    fn triangulates_quad_faces() {
        // A single quad -> two triangles, four shared vertices.
        let quad = "\
v 0 0 0
v 1 0 0
v 1 1 0
v 0 1 0
f 1 2 3 4
";
        let path = temp_obj(quad, "quad");
        let scene = load_obj(&path).expect("quad should load");
        std::fs::remove_file(&path).ok();

        assert_eq!(scene.triangle_count(), 2);
        assert_eq!(scene.vertex_count(), 4);
    }

    #[test]
    fn missing_file_is_err_not_panic() {
        let err = load_obj("does-not-exist-12345.obj");
        assert!(matches!(err, Err(Error::Decode(_))));
    }

    #[test]
    fn malformed_input_is_err() {
        // A face referencing a vertex that was never declared is malformed.
        let bad = "v 0 0 0\nf 1 2 3\n";
        let path = temp_obj(bad, "malformed");
        let result = load_obj(&path);
        std::fs::remove_file(&path).ok();
        assert!(result.is_err(), "malformed OBJ must return Err");
    }
}
